### ISSUE TITLE
"DataInputStreams" can only read one word at a time

### ISSUE THREAD

**Issue by wafsek** [wafsek/trafikk-lights#1]
"DataInputStream" can only read one word at a time. For this reason i am going to change Streams so that a whole line can be send and received. This may affect both client side and server side. I will commit the changes as soon as i can.

**Comment by Adsime** [comment]
Just brief me on what ever change you make. Should be an easy fix. Object streams will probably be sufficient

On Tue, Feb 16, 2016 at 11:17 AM -0800, "Baljit Singh Sarai" notifications@github.com wrote:

"DataInputStream" can only read one word at a time. For this reason i am going to change Streams so that a whole lline can be send and recived. This may affect both client side and server side.

---

Reply to this email directly or view it on GitHub:
https://github.com/wafsek/trafikk-lights/issues/1

**Comment by wafsek** [comment]
I tried to fix the problem only to introduce a big security/mistake risk. You see when server allows for unlimited data at one "read" then there is a risk that either by mistake or willingly(which is less likely, I know) you could send unnecessary long message for ex. entire files. I have come to the conclusion that we might need to limit the size of the message. Will commit when i am done with this. :)
